homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: 258
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensor.yaml

device_tracker:
  platform: tomato
  host: 192.168.1.1
  username: !secret tomato_username
  password: !secret tomato_password
  http_id: !secret tomato_http_id
  track_new_devices: no

#automation: !include_dir_merge_list automation

media_player:
  platform: plex

group: !include group.yaml

script: !include_dir_merge_named script/

#notify: !include notify.yaml