- alias: "Home and away notification"
  trigger:
    - platform: state
      entity_id: group.all_devices
  action:
    service: script.join_notify
    data:
      notification_message: "This is a message"