- alias: "Home and away notification"
  trigger:
    - platform: state
      entity_id: group.all_devices
  action:
    service: script.turn_on
    data:
      {"entity_id":"script.join_notify","variables": {"message": "Did this one work?","name": "Paulus"}}